package com.delegation.horizon.model

//Document to contain details of insuree profile
// Eg. HORZ0041 -> AUTOGENERATED insureeId
//     name -> horizonCustomer
//     address -> Grove Street
//     email -> customer@horizon.in
//     phone -> 1234567890
//     insuranceType -> motor/travel/health/bike

import org.springframework.data.annotation.Id
import org.springframework.data.mongodb.core.mapping.Document

@Document
class Insuree {

    @Id
    var insureeId = ""
    var name = ""
    var address = ""
    var email = ""
    var phone = ""
    var insuranceType = ""


}