package com.delegation.horizon.model

//Holds details for the list of motor vehicles in database
//Eg. Toyota -> motorMake
//    Prius -> motorModel
//    MOTR0041 -> AUTOGENERATED motorStoreId

import org.springframework.data.annotation.Id
import org.springframework.data.mongodb.core.mapping.Document

@Document
class MotorStore {

    @Id
    var motorStoreId = ""
    var motorCompany = ""  //TATA
    var motorModel = "" //NANO
    var exShowroomPrice = "" // 500000
    var engineCc = "" // 2300



}