package com.delegation.horizon.service

import com.delegation.horizon.model.PartnerMapping
import com.delegation.horizon.repository.PartnerMappingRepository
import com.delegation.horizon.request.MappingRequestDTO
import org.json.simple.JSONArray
import org.json.simple.JSONObject
import org.springframework.stereotype.Service
import java.io.FileOutputStream
import java.io.FileWriter
import java.io.IOException
import java.nio.file.Files
import java.nio.file.Path
import java.util.*


@Service
class UtilityService(val partnerMappingRepository: PartnerMappingRepository, val motorInsuranceService: MotorInsuranceService) {


    fun generateJSONFile(jsonRequest: JSONObject) : JSONObject{




        try{
            val fileWriter =  FileWriter("partnerMapping.json")
            println("Writing to file")
            fileWriter.write(jsonRequest.toJSONString())
            fileWriter.flush()
            val partnerMapping = PartnerMapping()
            partnerMapping.mappingId = motorInsuranceService.generateId()
            partnerMapping.mappingContent = jsonRequest.toJSONString()
            partnerMappingRepository.save(partnerMapping)
        }
        catch (e:IOException) {
            e.printStackTrace()
        }
        println("JSON Object=")
        println(jsonRequest)

        return jsonRequest
    }
    fun generatePropertiesFile(templateData: MappingRequestDTO): String {
        val props = Properties()
        props["TemplateName"] = templateData.templateName
        props["InsuranceType"] = templateData.insuranceType

        //Instantiating the FileInputStream for output file
        //Instantiating the FileInputStream for output file
        val path = "src\\main\\resources\\partner.properties"
        val outputStream = FileOutputStream(path)
        //Storing the properties file
        //Storing the properties file
        props.store(outputStream, "Autogenerated Partner Mapping")
        println("Properties file created......")

        return readPropertiesFile()

    }

    fun readPropertiesFile(): String {
        val path = "src\\main\\resources\\partner.properties"
//        val fr = FileReader(path)
//        val a = CharArray(500)
//       var string: String = String(a)
//        fr.read(a) // reads the content to the array
        val fileName: Path = Path.of(path)

        // Now calling Files.readString() method to
        // read the file

        // Now calling Files.readString() method to
        // read the file
        val str: String = Files.readString(fileName)


//        for (c in a) print(c) // prints the characters one by one

        println(str)

        val partnerMapping = PartnerMapping()
        partnerMapping.mappingId = motorInsuranceService.generateId()
        partnerMapping.mappingContent = str
        partnerMappingRepository.save(partnerMapping)


//        fr.close()
        return partnerMapping.mappingContent

    }
}