version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t horizon-app:latest .
      - docker tag simpleapi:latest 681883126489.dkr.ecr.ap-south-1.amazonaws.com/horizon-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 681883126489.dkr.ecr.ap-south-1.amazonaws.com/horizon-app:latest